version: "2"

services:
    nginx:
        ports:
            - "80:80"
        image: nginx:1.13
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./www:/var/www/site
        networks:
            - back-tier

volumes:
    mongo-data-wt:
        driver: local

networks:
    back-tier:
        driver: bridge
